fail_fast: true
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.4.0
    hooks:
      - id: check-added-large-files
        name: use git LFS for large files
        args: ["--maxkb=100"]
      - id: check-case-conflict
      - id: check-merge-conflict
      - id: check-docstring-first
      - id: check-ast
      - id: trailing-whitespace
        args: [--markdown-linebreak-ext=md]
      - id: end-of-file-fixer
      - id: mixed-line-ending
        args: ["--fix=lf"]
      - id: check-yaml
      - id: check-toml
      - id: check-json
      - id: debug-statements
      - id: name-tests-test
  - repo: https://github.com/asottile/pyupgrade
    rev: v2.11.0
    hooks:
      - id: pyupgrade
        name: pyupgrade (you might have to git add files again)
  - repo: https://github.com/pre-commit/pygrep-hooks
    rev: v1.8.0
    hooks:
      - id: rst-backticks
      - id: python-no-log-warn
      - id: python-no-eval
      - id: python-check-mock-methods
  - repo: https://github.com/psf/black
    rev: 20.8b1
    hooks:
      - id: black
        name: Black formatter (you might have to git add files)
        args: [--safe, --quiet]
