[build-system]
requires = ["setuptools>=57", "wheel", "setuptools_scm>=6.3"]
build-backend = "setuptools.build_meta"

[tool.setuptools_scm]
write_to = "src/requsim/version.py"
local_scheme = "no-local-version"
