# tests for now, will include artifacts and release later
name: Tests, Artifacts and Release

on:
  pull_request:
  push:
    branches:
      - main
      - dev
    tags:
      - "*.*"
      - "v*.*"
  release:

jobs:

  pre-commit:
    name: Check code quality
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v3
        with:
          python-version: '3.8'
      - uses: pre-commit/action@v2.0.3

  test_pipenv:
    name: Run tests in development environment with pipenv
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v3
        with:
          python-version: '3.8'
      - run: pip install pipenv
      - run: pipenv sync --dev
      - run: pipenv run pytest

  check_install:
    runs-on: ubuntu-latest
    name: Check package installation via setup.py works
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v3
        with:
          python-version: '3.8'
      - run: pip install --upgrade setuptools
      - name: Build package
        run: python setup.py sdist
      - name: Install package
        run: pip install dist/*

  test_general:
    needs: check_install
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        python-version: ['3.8', '3.9', '3.10']
      fail-fast: false
    runs-on: ${{ matrix.os }}
    name: Run Tests on ${{ matrix.os }} - Python ${{ matrix.python-version }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
      - run: pip install --upgrade setuptools
      - run: pip install -e ./[test]
      - run: pytest

  dist:
    name: Python bdist/wheel
    needs: [pre-commit, test_pipenv, test_general]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Fetch all tags, so setuptools_scm can determine version
        run: git fetch --prune --unshallow --tags
      - uses: actions/setup-python@v3
        with:
          python-version: '3.8'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install --upgrade wheel setuptools setuptools_scm
      - name: Build package
        run: python setup.py sdist bdist_wheel
      - uses: actions/upload-artifact@v2
        with:
          name: dist
          path: dist

  dist_check:
    needs: [dist]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v3
        with:
          python-version: '3.8'
      - name: Install dependencies
        run: pip install twine
      - uses: actions/download-artifact@v2
        with:
          name: dist
          path: dist
      - run: twine check dist/*


  dist_upload_test_pypi_only:
    if: github.event.ref == 'refs/heads/dev'
    runs-on: ubuntu-latest
    needs: [dist_check]
    steps:
      - uses: actions/download-artifact@v2
        with:
          name: dist
          path: dist
      - name: Publish distribution to Test PyPI
        uses: pypa/gh-action-pypi-publish@v1.5.0
        with:
          user: __token__
          password: ${{ secrets.test_pypi_token }}
          repository_url: https://test.pypi.org/legacy/
          skip_existing: true


  dist_upload_pypi:
    if: startsWith(github.event.ref, 'refs/tags')
    runs-on: ubuntu-latest
    needs: [dist_check]
    steps:
      - uses: actions/download-artifact@v2
        with:
          name: dist
          path: dist
      - name: Publish package to PyPI
        uses: pypa/gh-action-pypi-publish@v1.5.0
        with:
          user: __token__
          password: ${{ secrets.pypi_token }}
      - name: Publish distribution to Test PyPI
        uses: pypa/gh-action-pypi-publish@v1.5.0
        with:
          user: __token__
          password: ${{ secrets.test_pypi_token }}
          repository_url: https://test.pypi.org/legacy/
          skip_existing: true
